rm(list = ls())
source("analysis scripts/1 unodc.R")
source("analysis scripts/2 dhs.R")
source("analysis scripts/2 mics.R")
source("analysis scripts/2 unece.R")
source("analysis scripts/2 unicef.R")
source("analysis scripts/3 dhs.R")
source("analysis scripts/3 eurostat.R")
source("analysis scripts/4 mics.R")
source("analysis scripts/9 transmonee.R")
source("analysis scripts/10 oecd.R")
source("analysis scripts/10 tmee hbsc.R")
source("analysis scripts/10 tmee hbsc cb.R")
source("analysis scripts/10 tmee ilo.R")
source("analysis scripts/10 unicef.R")
source("analysis scripts/10 unodc.R")
source("analysis scripts/11 mics.R")
source("analysis scripts/11 tmee.R")
